### PR TITLE
ADD:XIRR calculator

### PR DESCRIPTION
**Pull request by URVESH1121**

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
Tests are failing

**Comment by URVESH1121** [comment]
> Tests are failing

Now check it!

**Comment by bharathkumarchowdary** [comment]
there should be an option for selecting irregular investments. Current implementation is for monthly regular fixed investment. XIRR or IRR is for irregular investment/disbursements. SIP is for regular investments

**Comment by URVESH1121** [comment]
> there should be an option for selecting irregular investments. Current implementation is for monthly regular fixed investment. XIRR or IRR is for irregular investment/disbursements. SIP is for regular investments

ok

**Pull request closed without merging**
