### PR TITLE
feat: updated simulation chart to apex chart

### PR DESCRIPTION
**Pull request by imhardikdesai**
@mohitkhatri06 @bharathkumarchowdary please review PR
- I have updated scenarios simulate chart to apex chart
image

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 , your review is required here

**Review by mohitkhatri06 — APPROVED** [review]

**Comment by imhardikdesai** [comment]
I have added the following fixes
- Fixed the issue of live (user who have not first_name) they can not able to create scenarios 
- make scenarios available public #509 
- Added error boundary for user

@bharathkumarchowdary @mohitkhatri06

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- In the graph of simulation results, hover tooltip on graph only shows for one line for multiline chart
image
- User 1 creates a public comparison and shares with user 2 the link. User 2 logs in and goes to given link. It doesn't work. that's a problem.
- Users/Visitors should have option to copy a public comparison to their profile when they come from a shared link, such that they can edit their copy of comparisons/scenarios 
- In Asset Creation UI of Scenarios, add flow for Mutual Funds. Refer swagger docs

**Comment by bharathkumarchowdary** [comment]
@imhardikdesai , there are conflicts in this PR

**Pull request closed without merging**
