### PR TITLE
268 XIRR Calculator implementation

### PR DESCRIPTION
**Pull request by nanipunepalle**

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
It's better to rearrange fields in calculator to show in a tabular form
image

**Comment by nanipunepalle** [comment]
image

confirm if this looks fine

**Comment by bharathkumarchowdary** [comment]
> image
> confirm if this looks fine

Looks good! Can I also type the dates along with able to select with calendar dropdown. I'm asking this to evaluate whether I can type all entries and calculate just using keyboard not using mouse

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary previous url broken when were were migrating from the javascript to the type script, for the next time we will not change anything, until it is needed to be add

Thank you @mohitkhatri06 .. Don't you think having a simple unit test for that helps here?

**Comment by mohitkhatri06** [comment]
@nanipunepalle please handle the following case and resolve the App.jsx conflicts

image

**Comment by bharathkumarchowdary** [comment]
@imhardikdesai , there are conflicts in this PR

**Pull request closed without merging**
