### PR TITLE
Goals with Step component.

### PR DESCRIPTION
**Pull request by Sandip-Z**
This PR contains 
#473 - Adding info regarding goal in create goal page.
#464 - Make goal creation in steps and add a multiply by field for KPI type Cash.

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
1. steppers are very far from each other those should be near to each other, as we don't have much steps
2.  next and prev buttons should have some gap between them 
3.  disable buttons when we are processing the task of create 

https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/aacfada8-ee8e-486d-a3ab-32bda87ed436

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
In step 2, we discussed about these points and were not implemented

- Contribution source is not required parameter. user should be aware of it
- All fields should have help icon hovering upon which help text should float. There should be thousands of UI libraries/packages online which can implement this
- Add more text on multiplier field explaining what it does. "Set a cash target to meet x months of expenses" - this sounds better
- Why should we have such a long input text field just for an integer which is expected to hold barely 2 digits? Be sensible of how the UI looks

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
In goal detail page, please add option for user to edit each field in-place
Back to goals button doesn't feel like button, since it doesn't change cursor style when over it
edit goal is not working if I don't give contrib source

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z This branch is out-of-date with the base branch

**Comment by mohitkhatri06** [comment]
@Sandip-Z  so here target can be % and any numerical value also for an example 90000

**Comment by Sandip-Z** [comment]
> @Sandip-Z so here target can be % and any numerical value also for an example 90000?

@mohitkhatri06 target is just a number with no upper limit set in frontend. It is not a percent value. Do we need to set any upper limit?

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , there are conflicts on this PR, please resolve

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
For a goal timeline that spans > 20 years, the page is loading too many times and too slow. I observed in the network tab that backend is giving data within 3seconds. Also the data is being loaded onto graph even after first reload and is obstructing the UI/UX for any small change on the page

**Comment by Sandip-Z** [comment]
> For a goal timeline that spans > 20 years, the page is loading too many times and too slow. I observed in the network tab that backend is giving data within 3seconds. 

@bharathkumarchowdary, the data provided by backend is raw data which is being converted in the frontend to display it in day/week/month/year wise, thus the slow loading. 

> Also the data is being loaded onto graph even after first reload and is obstructing the UI/UX for any small change on the page

I couldn't recreate this issue. Can you provide me a screen recording for this please?

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- Axios versio update to 1.7.3 is needed. I found it out via npm audit fix
- Create a separate step for KPI. Explain in it what each one is. KPI or Custom KPI is a choice. It should be either this or that
- help text for target and source fields are reversed

**Comment by bharathkumarchowdary** [comment]
Closing it since the design for Goals CRUD UI is updated

**Pull request closed without merging**
